# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Vitals.Vitals
PackageVersion: 0.9.0-beta.1
InstallerType: nullsoft
Scope: machine
InstallModes:
  - interactive
  - silent
UpgradeBehavior: install
ReleaseDate: 2026-09-28
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/dragoscv/vitals/releases/download/v0.9.0-beta.1/Vitals_0.9.0-beta.1_x64-setup.exe
    InstallerSha256: A50491CCA9D2BB2E2FA726BB3B9980B8E1BCF8A2975BDEF9E595EE4FB2A45CD8
  - Architecture: arm64
    InstallerUrl: https://github.com/dragoscv/vitals/releases/download/v0.9.0-beta.1/Vitals_0.9.0-beta.1_arm64-setup.exe
    InstallerSha256: 61D512EE5BA5485ED2297B21D05A79DF9704091D53FD17099B3BCF6CD866C914
ManifestType: installer
ManifestVersion: 1.12.0
